### ISSUE TITLE
email Input field in the Solana wallet adapter has less width

### ISSUE THREAD

**Issue by 0xPratik** [torusresearch/solana-wallet#212]
**Describe the bug**
The bug is in the input field of the torus email input field.

**To Reproduce**
1. Go to 'https://solana-labs.github.io/wallet-adapter/example/' on a browser not having wallet extensions
2. Click on 'select wallet'
3. Scroll down to 'in the initial modal with the email input box'
4. Write your email address and it would scroll horizontally

**Expected behavior**
There is a lot of space for the email id to fit but it gets cut in the middle.

**Screenshots**
<img width="796" alt="Screenshot 2022-03-01 at 1 13 42 PM" src="https://user-images.githubusercontent.com/62953475/156126310-d0913d3a-ad0f-4d49-82df-6af033b8d3c8.png">

In this screenshot i have written the complete email but it does not appears completely and scrolls

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser Chrome
 - Version M1 mac

**Comment by ieow** [comment]
![Screenshot 2022-03-29 at 10 54 45 AM](https://user-images.githubusercontent.com/4881057/160523771-c180d448-c84c-4457-91f4-e67e8b8f49f6.png)

OS: MAC
Browser Chrome
Version M1 Mac


Close this issue as it work fine now.
Feel free to reopen the issue if it reoccur
