### ISSUE TITLE
embed wallet popup is not working in MacOs safari

### ISSUE THREAD

**Issue by ieow** [torusresearch/solana-wallet#260]
due to safari bug where localstorage is not persistent. 
https://bugs.webkit.org/show_bug.cgi?id=225344

The popup wallet not able to restore key

**Comment by ieow** [comment]
longer flow needed to acquire Storage Access API 
https://webkit.org/blog/11545/updates-to-the-storage-access-api/

**Comment by ieow** [comment]
It seems like the Storage Access API is only for cookies
webstorage like localstorage and indexdb are still partitioned 

https://github.com/privacycg/storage-access/issues/4
https://github.com/privacycg/storage-access/issues/95

**Comment by arichiv** [comment]
There's an origin trial for accessing unpartitioned local storage and indexed db: https://developer.chrome.com/blog/saa-non-cookie-storage/
