### ISSUE TITLE
Update wallet loader to Web3Auth whitelabel loader

### ISSUE THREAD

**Issue by itsinz** [torusresearch/solana-wallet#286]
Current:
<img width="1440" alt="Screenshot 2022-05-06 at 1 01 26 PM" src="https://user-images.githubusercontent.com/53069682/167071470-bb988527-bbe8-422c-b054-565e3541115c.png">
Please update it to:
<img width="524" alt="Screenshot 2022-05-06 at 1 19 55 PM" src="https://user-images.githubusercontent.com/53069682/167071740-d2e35568-267f-45f6-9bc2-d5886bf4b0f6.png">

**Comment by metallicalfa2** [comment]
@guru-web3
